all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/coursework_ed25519

  children:
    bastion_host:
      hosts:
        bastion:
          ansible_host: 51.250.4.123
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    web:
      hosts:
        web-a:
          ansible_host: 10.0.1.17
        web-b:
          ansible_host: 10.0.2.17
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@51.250.4.123"

    prometheus:
      hosts:
        prometheus-server:
          ansible_host: 10.0.1.15
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@51.250.4.123"

    grafana:
      hosts:
        grafana-server:
          ansible_host: 10.0.10.26
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@51.250.4.123"

    elasticsearch:
      hosts:
        elasticsearch-server:
          ansible_host: 10.0.1.14
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@51.250.4.123"

    kibana:
      hosts:
        kibana-server:
          ansible_host: 10.0.10.34
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@51.250.4.123"
