all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/coursework_ed25519

  children:
    bastion:
      hosts:
        bastion:
          ansible_host: 84.252.129.36
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    web:
      hosts:
        web-a:
          ansible_host: 10.0.1.18
        web-b:
          ansible_host: 10.0.2.11
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -i ~/.ssh/coursework_ed25519 -o StrictHostKeyChecking=no -W %h:%p ubuntu@84.252.129.36"
