---
- name: Установить необходимые пакеты для snap
  apt:
    name:
      - snapd
    state: present
  become: yes

- name: Установить Grafana через snap
  snap:
    name: grafana
    classic: yes
    state: present
  become: yes

- name: Создать пользователя grafana (для совместимости с provisioning)
  user:
    name: grafana
    system: yes
    shell: /bin/false
    home: /var/lib/grafana
    create_home: yes
    state: present
  become: yes

- name: Создать директории для provisioning
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana
    mode: 0755
  loop:
    - "{{ grafana_datasources_dir }}"
    - "{{ grafana_dashboards_dir }}"
  become: yes

- name: Создать конфигурацию Grafana
  template:
    src: grafana.ini.j2
    dest: /var/snap/grafana/common/conf/grafana.ini
    owner: grafana
    group: grafana
    mode: 0640
  become: yes
  notify: Restart grafana

- name: Настроить datasource для Prometheus
  template:
    src: prometheus_datasource.yml.j2
    dest: "{{ grafana_datasources_dir }}/prometheus.yml"
    owner: grafana
    group: grafana
    mode: 0640
  become: yes
  notify: Restart grafana

- name: Развернуть кастомный дашборд под задание (USE-метрики + тресхолды)
  ansible.builtin.template:
    src: custom_dashboard.json.j2
    dest: "{{ grafana_dashboards_dir }}/custom_dashboard.json"
    owner: grafana
    group: grafana
    mode: "0644"
  become: yes
  notify: Restart grafana

- name: Настроить provisioning для дашбордов
  template:
    src: dashboards.yml.j2
    dest: "{{ grafana_dashboards_dir }}/dashboards.yml"
    owner: grafana
    group: grafana
    mode: 0640
  become: yes
  notify: Restart grafana

- name: Скачать JSON дашбордов
  get_url:
    url: "{{ item.url }}"
    dest: "{{ grafana_dashboards_dir }}/{{ item.id }}.json"
    owner: grafana
    group: grafana
    mode: 0644
  loop:
    - { id: 1860, url: "https://grafana.com/api/dashboards/1860/revisions/latest/download" }  # Node Exporter Full
    - { id: 12708, url: "https://grafana.com/api/dashboards/12708/revisions/latest/download" } # Nginx Exporter
    - { id: 11074, url: "https://grafana.com/api/dashboards/11074/revisions/latest/download" } # Prometheus Stats
  become: yes

- name: Заменить шаблонный datasource UID на реальный
  ansible.builtin.replace:
    path: "{{ grafana_dashboards_dir }}/{{ item.id }}.json"
    regexp: '\$\{DS_[A-Z0-9_]*\}'
    replace: 'prometheus'
  loop:
    - { id: 1860 }
    - { id: 12708 }
    - { id: 11074 }
  become: yes

- name: Исправить права доступа для provisioning (чтобы snap-демон мог читать)
  shell: |
    chmod -R 755 /var/snap/grafana/common/conf/provisioning
    find /var/snap/grafana/common/conf/provisioning -type f -exec chmod 644 {} \;
  become: yes
  tags: permissions

- name: Запустить и включить Grafana
  systemd:
    name: snap.grafana.grafana
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

