---
- name: Перезагрузить systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Перезапустить nginx_log_exporter
  ansible.builtin.systemd:
    name: nginx_log_exporter
    state: restarted