---
- name: Установить и настроить nginx на web-серверах
  hosts: web
  become: true

  roles:
    - nginx

- name: Настроить exporters на web-серверах
  hosts: web
  become: true

  roles:
    - node_exporter
    - nginx_exporter
    - nginx_log_exporter
    - filebeat

- name: Установить и настроить Elasticsearch
  hosts: elasticsearch
  become: true

  roles:
    - elasticsearch

- name: Установить и настроить Kibana
  hosts: kibana
  become: true

  roles:
    - kibana

- name: Установить и настроить Prometheus
  hosts: prometheus
  become: true

  roles:
    - prometheus

- name: Установить и настроить Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana

